#!/bin/sh
NAME="cpu"
. ${LIBEXEC}/common
if checkyesno "${NAME}_enable"; then
	moreverbosen "Detecting operating system..."
	OS=$(uname)
	moreverbose "${OS}"
	moreverbosen "cpu: checking usage: "
	case ${OS} in
		NetBSD)
			IDLE=$(top | head -n 3 | tail -n 1 | awk -F, '{print $5}' | awk -F. '{print $1}' | awk -F'%' '{print $1}')
			;;
		FreeBSD)
			IDLE=$(top | head -n 3 | tail -n 1 | awk -F, '{print $5}' | awk -F. '{print $1}' | awk -F'%' '  {print $1}')
			;;
		DragonFly)
			IDLE=$(top | head -n 3 | tail -n 1 | awk -F, '{print $5}' | awk -F. '{print $1}' | awk -F'%' '  {print $1}')
			;;
		OpenBSD)
			IDLE=$(top | head -n 3 | tail -n 1 | awk -F, '{print $6}' | awk -F. '{print $1}' | awk -F'%' '  {print $1}')
			;;
		SunOS)
			IDLES=$(mpstat | grep -v CPU | awk '{print $16}')
			IDLE=0
			for curidle in ${IDLES}; do
				if [ "${curidle}" -gt ${IDLE} ]; then
					IDLE=${curidle}
				fi
			done
			;;
		Linux)
			IDLE=$(top -b -n 1 | head -n 3 | tail -n 1 | awk -F ',' '{print $4}' | awk '{print $1}' | awk -F. '{print $1}')
			;;
	esac
	USAGE=$((100 - ${IDLE}))
	moreverbose ${USAGE}%
	if [ ${USAGE} -gt ${cpu_threshold} ]; then
		alert "${NAME}" "cpu usage: ${USAGE}%"
	fi
fi
